### PR TITLE
Warn user of malformed config

### LINKED ISSUE #35: Warn user on malformed config in localStorage
See convo #33 

We shouldn't fail, but rather ignore the error and load the app with a warning.

### PR DESCRIPTION
**Pull request by axelchalon**
closes #35 

Previous behaviour : when loading a config where the types don't match with the current format, parity-config-generator might crash because it assumes the types are correct (for displaying in the editor for example). Example: http://paritytech.github.io/parity-config-generator/#config=eyJuZXR3b3JrIjp7InJlc2VydmVkX3BlZXJzIjpbImZpcnN0cGF0aCIsInNlY29uZHBhdGgiXX19 This can happen if the type of an item changed with a commit, like in https://github.com/paritytech/parity-config-generator/commit/874133549b5d998bcbdadcc2c16e587ab5f4dc8a

This PR instead displays a warning (to make sure the user knows that the setting will be ignored) and sets the malformed config item to the default value. Added a Modal component and updated React dependency to be able to use `<Fragment>` (with the new version, PropTypes have been moved to a separate repo).

image

### CODE REVIEW

File: src/App.js [hunk 1]
```diff
@@ -49,22 +50,27 @@ function loadSettings () {
...
     if (settings && typeof settings === 'object') {
       // make sure the sections are always created
+      const errors = [];
       Object.keys(defaultSettings).forEach(key => {
         settings[key] = settings[key] || {};
         Object.keys(defaultSettings[key]).forEach(prop => {
           if (settings[key][prop] === undefined) {
             settings[key][prop] = defaultSettings[key][prop];
+          } else if (typeof settings[key][prop] !== typeof defaultSettings[key][prop]) {
+            errors.push({section: key, prop, value: settings[key][prop], type: typeof settings[key][prop], expected: typeof defaultSettings[key][prop]});
```
Comment (tomusdrw) [inline src/App.js]: can we expand this line a bit? Would rather see each key on a separate line.

Perhaps it's also make sense to extract `settings[key]` and `defaultSettings[key][prop]` to separate variables cause they are now used quite often.

File: src/components/Modal.js [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+  }
+
+  componentDidMount () {
+    const dialog = ReactDOM.findDOMNode(this);
+    if (!dialog.showModal) {
+      dialogPolyfill.registerDialog(dialog);
+    }
+
+    if (this.props.title) {
+      setTimeout(this.show.bind(this), 100);
```
Comment (tomusdrw) [inline src/components/Modal.js]: I'd prefer a lambda here: `setTimeout(() => this.show(), 100);`

File: src/components/Modal.js [hunk 3]
```diff
@@ -0,0 +1,58 @@
...
+    }
+  }
+
+  componentDidUpdate (prevProps) {
+    if (prevProps.title && !this.props.title) {
```
Comment (tomusdrw) [inline src/components/Modal.js]: Why not have an explicit `visible` prop instead?

**Review by tomusdrw — COMMENTED** [review]
Awesome! I have couple of grumbles regarding modal, but I like the functionality.

Any reason for implementing dialogs yourself? There should be some libraries for that, no?

**Comment by axelchalon** [comment]
Thanks for the review :)

I saw you were using material design lite so I implemented what I saw here to stay in the guidelines: https://getmdl.io/components/index.html#dialog-section
The logic was pretty simple so I figured I'd do it myself; couldn't find a mdl modal react component (https://github.com/tleunen/react-mdl is deprecated and the replacement doesn't use mdl afaik) and I figured it'd be more hassle to use an existing modal component and adapt it to mdl

File: src/components/Modal.js (hunk 3 above)
Comment (axelchalon) [reply src/components/Modal.js]: Hmm, seems a bit redundant to me. Then we could have the props title & content with a value, but visible to false, and then the modal would be closed but would still have information about title/content, which seems strange to me... what do you think?

Comment (tomusdrw) [reply src/components/Modal.js]: It doesn't sound intuitive to me to remove a `title` to close the dialog. All other dialog libraries I used for react follow this pattern, have a look here:
https://github.com/reactjs/react-modal

If you want to optimize displaying the dialog instead of setting `isOpen/visible` to `false` you could just remove it from the DOM entirely.
Using `visible=false/true` also allows you to animate opening/closing, while removing the title and content would break that.

Comment (axelchalon) [reply src/components/Modal.js]: OK! Makes sense

I think since we're using HTML5 `<dialog>` it's better to use the native close rather than remove the element (for possibly native animations etc. in the future)

Committed; let me know what you think
